apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: todo-frontend
spec:
  selector:
    matchLabels:
      app: todo-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: todo-frontend
          image: tarek5/todo-grpc-frontend:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://192.168.99.100/api"
          ports:
            - name: todo-f-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 8096
      nodePort: 30096
      targetPort: todo-f-port